/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FollowRouteImport } from './routes/follow'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as PoliciesReturnsRouteImport } from './routes/policies.returns'
import { Route as PoliciesShippingRouteImport } from './routes/policies.shipping'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowRoute = FollowRouteImport.update({
  id: '/follow',
  path: '/follow',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesReturnsRoute = PoliciesReturnsRouteImport.update({
  id: '/policies/returns',
  path: '/policies/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesShippingRoute = PoliciesShippingRouteImport.update({
  id: '/policies/shipping',
  path: '/policies/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/follow': typeof FollowRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/search': typeof SearchRoute
  '/thank-you': typeof ThankYouRoute
  '/category/$slug': typeof CategorySlugRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/product/$id': typeof ProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/follow': typeof FollowRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/search': typeof SearchRoute
  '/thank-you': typeof ThankYouRoute
  '/category/$slug': typeof CategorySlugRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/product/$id': typeof ProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/follow': typeof FollowRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/search': typeof SearchRoute
  '/thank-you': typeof ThankYouRoute
  '/category/$slug': typeof CategorySlugRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/product/$id': typeof ProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/follow'
    | '/login'
    | '/offers'
    | '/search'
    | '/thank-you'
    | '/category/$slug'
    | '/policies/returns'
    | '/policies/shipping'
    | '/product/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/follow'
    | '/login'
    | '/offers'
    | '/search'
    | '/thank-you'
    | '/category/$slug'
    | '/policies/returns'
    | '/policies/shipping'
    | '/product/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/follow'
    | '/login'
    | '/offers'
    | '/search'
    | '/thank-you'
    | '/category/$slug'
    | '/policies/returns'
    | '/policies/shipping'
    | '/product/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FollowRoute: typeof FollowRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  SearchRoute: typeof SearchRoute
  ThankYouRoute: typeof ThankYouRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PoliciesReturnsRoute: typeof PoliciesReturnsRoute
  PoliciesShippingRoute: typeof PoliciesShippingRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow': {
      id: '/follow'
      path: '/follow'
      fullPath: '/follow'
      preLoaderRoute: typeof FollowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/returns': {
      id: '/policies/returns'
      path: '/policies/returns'
      fullPath: '/policies/returns'
      preLoaderRoute: typeof PoliciesReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/shipping': {
      id: '/policies/shipping'
      path: '/policies/shipping'
      fullPath: '/policies/shipping'
      preLoaderRoute: typeof PoliciesShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FollowRoute: FollowRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  SearchRoute: SearchRoute,
  ThankYouRoute: ThankYouRoute,
  CategorySlugRoute: CategorySlugRoute,
  PoliciesReturnsRoute: PoliciesReturnsRoute,
  PoliciesShippingRoute: PoliciesShippingRoute,
  ProductIdRoute: ProductIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
